In [1]:
import sqlite3
import pandas as pd
from sqlalchemy import create_engine

In [2]:
db = create_engine('sqlite:///db_olist.sqlite',echo=False)
conn = db.connect()

In [3]:
## DATA READING
df_customer = pd.read_csv('DataBases/olist_customers_dataset.csv')
df_geolocation = pd.read_csv('DataBases/olist_geolocation_dataset.csv')
df_order_items = pd.read_csv('DataBases/olist_order_items_dataset.csv')
df_order_payments = pd.read_csv('DataBases/olist_order_payments_dataset.csv')
df_order_reviews = pd.read_csv('DataBases/olist_order_reviews_dataset.csv')
df_orders = pd.read_csv('DataBases/olist_orders_dataset.csv')
df_products = pd.read_csv('DataBases/olist_products_dataset.csv')
df_sellers = pd.read_csv('DataBases/olist_sellers_dataset.csv')
df_product_category_name = pd.read_csv('DataBases/product_category_name_translation.csv')

In [4]:
schema_customer = """
    CREATE TABLE customer(
    customer_id             text,
    customer_unique_id      text,
    customer_zip_code_prefix integer,
    customer_city           text,
    customer_state          text)

"""
schema_geolocation ="""
    CREATE TABLE geolocation(
    geolocation_zip_code_prefix    integer,
    geolocation_lat                real,
    geolocation_lng                real,
    geolocation_city               text,
    geolocation_state              text)

"""
schema_order_items = """
    CREATE TABLE order_items(
    order_id                text,
    order_item_id           integer,
    product_id              text,
    seller_id               text,
    shipping_limit_date     text,
    price                   real,
    freight_value           real)

"""
schema_order_payments = """
    CREATE TABLE order_payments(
    order_id                 text,
    payment_sequential       integer,
    payment_type             text,
    payment_installments     integer,
    payment_value            real)

"""
schema_order_reviews = """
    CREATE TABLE order_reviews(
    review_id                  text,
    order_id                   text,
    review_score                integer,
    review_comment_title       text,
    review_comment_message     text,
    review_creation_date       text,
    review_answer_timestamp    text)

"""
schema_orders = """
    CREATE TABLE orders(
    order_id                         text,
    customer_id                      text,
    order_status                     text,
    order_purchase_timestamp         text,
    order_approved_at                text,
    order_delivered_carrier_date     text,
    order_delivered_customer_date    text,
    order_estimated_delivery_date    text)

"""
schema_products = """
    CREATE TABLE products(
    product_id                     text,
    product_category_name          text,
    product_name_lenght           real,
    product_description_lenght    real,
    product_photos_qty            real,
    product_weight_g              real,
    product_length_cm             real,
    product_height_cm             real,
    product_width_cm              real)

"""
schema_sellers = """
    CREATE TABLE sellers(
    seller_id                 text,
    seller_zip_code_prefix    integer,
    seller_city               text,
    seller_state              text)

"""
schema_product_category_name = """
    CREATE TABLE product_category_name(
    
    product_category_name            text,
    product_category_name_english    text)

"""


# Create schema
conn.execute(schema_customer)
conn.execute(schema_geolocation)
conn.execute(schema_order_items)
conn.execute(schema_order_payments)
conn.execute(schema_order_reviews)
conn.execute(schema_orders)
conn.execute(schema_products)
conn.execute(schema_sellers)
conn.execute(schema_product_category_name)


# Insert data into table - Index = False para resetar no come√ßo
df_customer.to_sql('customer',con=conn,if_exists='append',index=False)
df_geolocation.to_sql('geolocation',con=conn,if_exists='append',index=False)
df_order_items.to_sql('order_items',con=conn,if_exists='append',index=False)
df_order_payments.to_sql('order_payments',con=conn,if_exists='append',index=False)
df_order_reviews.to_sql('order_reviews',con=conn,if_exists='append',index=False)
df_orders.to_sql('orders',con=conn,if_exists='append',index=False)
df_products.to_sql('products',con=conn,if_exists='append',index=False)
df_sellers.to_sql('sellers',con=conn,if_exists='append',index=False)
df_product_category_name.to_sql('product_category_name',con=conn,if_exists='append',index=False)

In [14]:
query = """
SELECT name
FROM sqlite_master
WHERE type = 'table' """

#query = """
#SELECT * 
#FROM CUSTOMER"""

table = pd.read_sql_query(query,conn)
table

Empty DataFrame
Columns: [customer_id, customer_unique_id, customer_zip_cod_prefix, customer_city, customer_state]
Index: []

In [60]:
query = """
SELECT name
FROM sqlite_master
WHERE type = 'table' """

#query = """
#SELECT * 
#FROM CUSTOMER"""

table = pd.read_sql_query(query,conn)
table

                    name
0               customer
1            geolocation
2            order_items
3         order_payments
4          order_reviews
5                 orders
6               products
7                sellers
8  product_category_name

## Check Database

In [15]:
#query = """
#SELECT name
#FROM sqlite_master
#WHERE type = 'table' """

query = """
SELECT * 
FROM product_category_name"""

table = pd.read_sql_query(query,conn)
table

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [18]:
table.head(50)

,product_category_name,product_category_name_english
0,beleza_saude,health_beauty
1,informatica_acessorios,computers_accessories
2,automotivo,auto
3,cama_mesa_banho,bed_bath_table
4,moveis_decoracao,furniture_decor
5,esporte_lazer,sports_leisure
6,perfumaria,perfumery
7,utilidades_domesticas,housewares
8,telefonia,telephony
9,relogios_presentes,watches_gifts
10,alimentos_bebidas,food_drink
11,bebes,baby
12,papelaria,stationery
13,tablets_impressao_imagem,tablets_printing_image
14,brinquedos,toys
15,telefonia_fixa,fixed_telephony
16,ferramentas_jardim,garden_tools
17,fashion_bolsas_e_acessorios,fashion_bags_accessories
18,eletroportateis,small_appliances
19,consoles_games,consoles_games
20,audio,audio
21,fashion_calcados,fashion_shoes
22,cool_stuff,cool_stuff
23,malas_acessorios,luggage_accessories
24,climatizacao,air_conditioning
25,construcao_ferramentas_construcao,construction_tools_construction
26,moveis_cozinha_area_de_servico_jantar_e_jardim,kitchen_dining_laundry_garden_furniture
27,construcao_ferramentas_jardim,costruction_tools_garden
28,fashion_roupa_masculina,fashion_male_clothing
29,pet_shop,pet_shop
30,moveis_escritorio,office_furniture
31,market_place,market_place
32,eletronicos,electronics
33,eletrodomesticos,home_appliances
34,artigos_de_festas,party_supplies
35,casa_conforto,home_confort
36,construcao_ferramentas_ferramentas,costruction_tools_tools
37,agro_industria_e_comercio,agro_industry_and_commerce
38,moveis_colchao_e_estofado,furniture_mattress_and_upholstery
39,livros_tecnicos,books_technical
40,casa_construcao,home_construction
41,instrumentos_musicais,musical_instruments
42,moveis_sala,furniture_living_room
43,construcao_ferramentas_iluminacao,construction_tools_lights
44,industria_comercio_e_negocios,industry_commerce_and_business
45,alimentos,food
46,artes,art
47,moveis_quarto,furniture_bedroom
48,livros_interesse_geral,books_general_interest
49,construcao_ferramentas_seguranca,construction_tools_safety